language: php

php:
  - "5.5"
  - "5.4"
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer update
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v
